version: '3.8'

services:
  # Servizio MariaDB
  mariadb:
    image: mariadb:10.11
    container_name: mariadb_container
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: app_database
      MYSQL_USER: app_user
      MYSQL_PASSWORD: app_password
    volumes:
      - mariadb_data:/var/lib/mysql
      - ./mysql/init:/docker-entrypoint-initdb.d
    ports:
      - "0.0.0.0:3306:3306"
    networks:
      - app_network

  # Servizio PHP-FPM
  php:
    build:
      context: ./php
      dockerfile: Dockerfile
    container_name: php_container
    restart: unless-stopped
    volumes:
      - ./src:/var/www/html
      - ./php/php.ini:/usr/local/etc/php/php.ini
    depends_on:
      - mariadb
    networks:
      - app_network

  # Servizio Nginx
  nginx:
    image: nginx:alpine
    container_name: nginx_container
    restart: unless-stopped
    ports:
      - "0.0.0.0:80:80"
      - "0.0.0.0:443:443"
    volumes:
      - ./src:/var/www/html
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - /etc/letsencrypt:/etc/letsencrypt:ro
    depends_on:
      - php
    networks:
      - app_network

volumes:
  mariadb_data:

networks:
  app_network:
    driver: bridge